kind: Service
apiVersion: v1
metadata:
  name: shcba-test-service
spec:
  selector:
    app: shcba-test
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shcba-test
  labels:
    app: shcba-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shcba-test
  template:
    metadata:
      labels:
        app: shcba-test
    spec:
      imagePullSecrets:
        - name: pipeline-docker-registry
      containers:
      - env:
        - name: APP_BUILD_ID
          value: '${CICD_EXECUTION_SEQUENCE}'
        image: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
        name: shcba-test
        ports:
        - containerPort: 8080